[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

# Optional: if you later add an API endpoint called "ask-eve-search"
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200
